export const IconHeartUpdate = "IconHeartUpdate"
export const OpenCategoryLayout = "OpenCategoryLayout"
export const ProfileLayoutUpdate =  "ProfileLayoutUpdate"
export const FavoredEventDataReduc = "FavoredEventData"
export const StoreExploreEventObj = "StoreExploreEventObj"